### ISSUE TITLE
Wave causes an extra, short lived replica to be created in every deployment

### ISSUE THREAD

**Issue by andrew-farries** [wave-k8s/wave#111]
Wave is causing an extra, short lived replica to be added to every deployment to which the `wave.pusher.com/update-on-config-change: "true"` annotation is added.

---

<details>
<summary><strong>Deployment manifest</strong></summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    wave.pusher.com/update-on-config-change: "true"
  labels:
    app: bbox
  name: bbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bbox
  template:
    metadata:
      labels:
        app: bbox
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - while true; do sleep 3600; done
        image: busybox
        name: busybox
```
</details>

Steps to replicate this:

First, install `wave`:

```
helm install wave wave-k8s/wave
```

Output of `helm ls`

```
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
wave    wave-test       1               2021-09-16 09:46:55.862965 +0100 BST    deployed        wave-2.0.0      v0.5.0
```

Apply the yaml file above:

```
kubectl apply -f deployment.yaml
```

I now see two pods start-up, one of which almost immediately enters a terminating state:

```
NAME                        READY   STATUS        RESTARTS   AGE   LABELS
bbox-57689566cf-8tc7p       1/1     Running       0          8s    app=bbox,pod-template-hash=57689566cf
bbox-68d685577f-p8s89       1/1     Terminating   0          8s    app=bbox,pod-template-hash=68d685577f
```

The pod in the `Terminating` state does not have the wave annotation; the `Running` one does.

Wave logs:

```
I0916 10:00:24.191390       1 handler.go:108] wave "level"=0 "msg"="Updating instance hash"  "hash"="100444e91862dd77d7ebe29f050c1e9a7f357c771e1a7b7650aae27e6a3a031d" "name"="bbox" "namespace"="wave-test"
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.16", GitCommit:"7a98bb2b7c9112935387825f2fce1b7d40b76236", GitTreeState:"clean", BuildDate:"2021-02-17T11:52:32Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

If I increase the replica count of the deployment to `2` I get four pods starting, two of which immediately enter a terminating state; as before the two 'extras' don't have the the wave annotation.

Removing the `wave.pusher.com/update-on-config-change: "true"` annotation from the deployment results in a deployment with no short-lived replicas, as expected.
