### ISSUE TITLE
changes to projected volumes not detected properly

### ISSUE THREAD

**Issue by sdahlbac** [wave-k8s/wave#127]
```yaml
    volumes:
      - configMap:
          defaultMode: 420
          name: kafka-jmx-configmap
          optional: false
        name: jmx-config
      - name: tls-conf
        projected:
          defaultMode: 420
          sources:
          - secret:
              name: kafka-secret
              optional: false
          - secret:
              items:
              - key: keystore.jks
                path: kafka-0-keystore.jks
              - key: truststore.jks
                path: truststore.jks
              name: kafka-0-tls-secret
              optional: false
          - secret:
              items:
              - key: keystore.jks
                path: kafka-1-keystore.jks
              name: kafka-1-tls-secret
              optional: false
          - secret:
              items:
              - key: keystore.jks
                path: kafka-2-keystore.jks
              name: kafka-2-tls-secret
              optional: false
```

If I trigger a certmanager renewal of a certificate, e.g. the `kafka-0-tls-secret` gets updated properly, but this is not detected by wave?
