### ISSUE TITLE
wave-system namespace finalizer prevents namespace deletion

### ISSUE THREAD

**Issue by Ghazgkull** [wave-k8s/wave#91]
The finalizer on the wave-system namespace prevents wave from being cleanly and completely removed from a cluster.

Attempts to delete the wave-system namespace simply hang forever.

**Comment by gargath** [comment]
Thanks for reporting this.

This is certainly not desired behaviour. I'll need to take a closer look when I get a chance and see about reproducing it.

In the meantime, once the Wave Deployment has been deleted, it should be safe to manually remove the finalizer using `kubectl edit` or similar and then deleting the namespace as usual.

**Comment by gargath** [comment]
Just to make sure I'm not making false assumptions, can you confirm how you deployed Wave in the first place? Did you use the Kustomization provided in this repo?

**Comment by jzelinskie** [comment]
I hand-wrote a deployment (to run in a single namespace) and had this same problem when I went to delete it.
The wave StatefulSet is just getting deleted before all of the deployments that it's managing.

**Comment by Ghazgkull** [comment]
Sorry for the slow reply. I missed the initial request for info.

We've got K8s manifests in our source control for deploying Wave, which I have to assume are based on the content provided in this repo. We use Terraform with the Kubernetes provider installed, so the manifests look a little different than normal Kustomize files.

Would love to use a Helm chart instead as per https://github.com/wave-k8s/wave/issues/81.

**Comment by gargath** [comment]
Helm charts are now hosted on Github Pages, please see the current README for details.

Would using those resolve this problem?

**Comment by Ghazgkull** [comment]
@gargath FYI, we've now using the helm chart and observing the same issue. I created a new "addons" namespace and put wave in it using the helm chart. Attempts to delete my "addons" namespace now hang forever.

**Comment by jzelinskie** [comment]
I'm still having this issue using these manifests, which are basically just the output of `helm template`:

<details>

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: wave
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wave
  namespace: wave
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: wave
  labels:
    app: wave
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["list", "get", "update", "patch", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets", "statefulsets"]
    verbs: ["list", "get", "update", "patch", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: wave
  labels:
    app: wave
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wave
subjects:
  - kind: ServiceAccount
    name: wave
    namespace: wave
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wave
  namespace: wave
  annotations:
    wave.pusher.com/update-on-config-change: "true"
spec:
  selector:
    matchLabels:
      app: wave
  template:
    metadata:
      labels:
        app: wave
    spec:
      serviceAccountName: wave
      containers:
      - name: wave
        image: quay.io/wave-k8s/wave:v0.5.0
```

</details>
