### ISSUE TITLE
Annotation(s) for additional CMs/Secrets to watch

### ISSUE THREAD

**Issue by aaron-trout** [wave-k8s/wave#98]
I have an initContainer on one of my deployments which reads stuff directly from a Kubernetes Secret. This doesn't currently get picked up by Wave because that Secret is not in any volumes or env/envFrom.

It would be handy if there was an optional annotation to specify extra configmaps / secrets to watch. Something like:

```
annotations:
  wave.pusher.com/update-on-config-change: "true"
  wave.pusher.com/extra-configmaps: "some-namespace/my-configmap"
  wave.pusher.com/extra-secrets: "some-namespace/my-secret,some-other-namespace/foo"
```

For now, I have worked around this by defining a Volume but not actually mounting it into any containers in the pod.
